services:
  master:
    build: { context: ., dockerfile: docker/Dockerfile }
    image: f1-hadoop:3.3.6
    container_name: master
    hostname: master
    ports: ["9870:9870", "8088:8088", "19888:19888"]
    volumes:
      - master-data:/hadoop/dfs
      - ./src:/project/src
      - ./scripts:/project/scripts
      - ./dataset:/project/dataset
      - ./output:/project/output
    networks: [hadoopnet]

  worker1:
    image: f1-hadoop:3.3.6
    container_name: worker1
    hostname: worker1
    depends_on: [master]
    volumes:
      - worker1-data:/hadoop/dfs
      - ./src:/project/src
    networks: [hadoopnet]

  worker2:
    image: f1-hadoop:3.3.6
    container_name: worker2
    hostname: worker2
    depends_on: [master]
    volumes:
      - worker2-data:/hadoop/dfs
      - ./src:/project/src
    networks: [hadoopnet]

  mongodb:
    image: mongo:7
    container_name: mongodb
    hostname: mongodb
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db
      - ./scripts:/scripts
      - ./output:/output
    networks: [hadoopnet]

volumes: { master-data: {}, worker1-data: {}, worker2-data: {}, mongo-data: {} }
networks: { hadoopnet: { driver: bridge } }